### ISSUE TITLE
Doesn't work for 2d triangular lattice

### ISSUE THREAD

**Issue by iintSjds** [jerjorg/SymmetryReduceBZ.jl#2]
Use code:

```julia
import SymmetryReduceBZ.Symmetry: calc_bz, calc_ibz
import SymmetryReduceBZ.Plotting: plot_2Dconvexhull
using PyPlot
real_latvecs = [1 0; 1/2 sqrt(3)/2]' # produce a triangular lattice
convention="ordinary"
atom_types=[0]
atom_pos = Array([0 0]')
coords = "Cartesian"
ibzformat = "convex hull"
makeprim=false
bz = calc_bz(real_latvecs,atom_types,atom_pos,coords,ibzformat,makeprim,convention)
ibz = calc_ibz(real_latvecs,atom_types,atom_pos,coords,ibzformat,makeprim,convention)
ax = plot_2Dconvexhull(bz,facecolor="deepskyblue",linewidth=3,edgecolor="cyan",alpha=0.2)
ax = plot_2Dconvexhull(ibz,ax;facecolor="coral",linewidth=3,edgecolor="magenta",alpha=0.4)
```
The result is not fully reduced.
![download](https://user-images.githubusercontent.com/12172181/152811547-0b210bf0-b81e-44f3-b0a4-bf484e114d2d.png)

**Comment by jerjorg** [comment]
The problem lies in the calculation of the point group where all the points within a circle/sphere are needed to compute the symmetries. The radius of the circle (in this case) was just barely too small and lattice points that lay on the boundary of the circle were being excluded due to finite precision. I've introduced a tolerance that fixes the issue in the latest commit.
